## Contains all the stages

stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/HR-Employee-Attrition.csv
    outs:
      - data/raw/HR-Employee-Attrition.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/HR-Employee-Attrition.csv
    outs:
      - data/raw/train_hr_employee_attrition.csv
      - data/raw/test_hr_employee_attrition.csv
  process_data:
    cmd: python src/process_data.py --config=params.yaml
    deps:
      - src/process_data.py
      - data/raw/train_hr_employee_attrition.csv
      - data/raw/test_hr_employee_attrition.csv
    outs:
      - data/processed/train_hr_employee_attrition.csv
      - data/processed/test_hr_employee_attrition.csv
      - saved_models/scaler.joblib
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_hr_employee_attrition.csv
      - data/processed/test_hr_employee_attrition.csv
      - src/train_and_evaluate.py
    params:
      - estimators.SVC.params.C
      - estimators.SVC.params.gamma
    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
    outs:
      - saved_models/model.joblib

#  log_production_model:
#    cmd: python src/log_production_model.py --config=params.yaml
#    deps:
#      - src/log_production_model.py
