## Contains all the configs

base:
  project: hr-amployee-attrition-project
  random_state: 123
  target_col: Attrition

data_source:
  s3_source: data_given/HR-Employee-Attrition.csv

load_data:
  raw_dataset_csv: data/raw/HR-Employee-Attrition.csv

preprocess:
  columns_to_drop: ['EmployeeNumber', 'EmployeeCount', 'StandardHours', 'Over18']
  train_path: data/processed/train_hr_employee_attrition.csv
  test_path: data/processed/test_hr_employee_attrition.csv

split_data:
  train_path: data/raw/train_hr_employee_attrition.csv
  test_path: data/raw/test_hr_employee_attrition.csv
  test_size: 0.3

estimators:
  SVC:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      C: 50
      gamma: 0.01
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://localhost:1234